apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels: #
      app: auth-deployment
  template:
    # applies to a pod : blueprint i.e how all deployments are define
    metadata:
      labels: # match labels creates connection. Pods get the label through
        # the template blueprint
        # helps deployment know which pods belong to it
        app: auth-deployment
    spec:
      containers:
        # specifies name of the container, which pod it is based on,
        # which port it should open
        - name: auth-deployment
          image: localhost:32000/auth-service:registry
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
