apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  clusterIP: None
  ports:
  - port: 15672
    targetPort: 15672
    name: discovery
  - port: 5672
    targetPort: 5672
    name: amqp
  #ports:
  #- port: 5672
    #targetPort: 15672
    #nodePort: 15672
  selector:
    app: taskQueue
    component: rabbitmq


---
apiVersion: v1
kind:  ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.8.3-management
        name: rabbitmq
        ports:
        - name: http
          protocol: TCP
          containerPort: 15672

        - name: amqp
          protocol: TCP
          containerPort: 5672
        resources:
          limits:
            cpu: 100m

